### ISSUE TITLE
manage.py celeryctl doesn't appear to work

### ISSUE THREAD

**Issue by cmheisel** [ask/flask-celery#8] opened 2011-08-03 15:07 UTC
I've got a Flask app using celery, I've confirmed that manage.py celeryd works just fine and is running.

But when I do any manage.py celeryctl command I get an error:

python manage.py celeryctl status
usage: manage.py celeryctl [-h]
manage.py celeryctl: error: unrecognized arguments: status

python manage.py celeryctl purge
usage: manage.py celeryctl [-h]
manage.py celeryctl: error: unrecognized arguments: purge

python manage.py celeryctl -h
usage: manage.py celeryctl [-h]

optional arguments:
  -h, --help  show this help message and exit

**Comment by ask** [comment] 2011-08-04 10:30
On 3 Aug 2011, at 16:07, cmheisel wrote:

> I've got a Flask app using celery, I've confirmed that manage.py celeryd works just fine and is running.
> 
> But when I do any manage.py celeryctl command I get an error:
> 
> python manage.py celeryctl status
> usage: manage.py celeryctl [-h]
> manage.py celeryctl: error: unrecognized arguments: status
> 
> python manage.py celeryctl purge
> usage: manage.py celeryctl [-h]
> manage.py celeryctl: error: unrecognized arguments: purge
> 
> python manage.py celeryctl -h
> usage: manage.py celeryctl [-h]
> 
> optional arguments:
>  -h, --help  show this help message and exit

Are you running Flask-Celery or Celery from git?

## 

Ask Solem
twitter.com/asksol | +44 (0)7713357179

**Comment by cmheisel** [comment] 2011-08-04 14:14
I'm calling manage.py celeryctl via Flask-Celery but here's what I've got installed:

celery==2.2.7
Flask-Celery==2.2.5

If I call path/to/my/venv/bin/celeryctl I get this traceback:

(kardboardve)cmheisel@li169-12:~$ celeryctl status
/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/loaders/default.py:54: NotConfigured: No 'celeryconfig' module found! Please make sure it exists and is available to Python.
  "is available to Python." % (configname, )))
Traceback (most recent call last):
  File "/home/cmheisel/kardboardve/bin/celeryctl", line 9, in <module>
    load_entry_point('celery==2.2.7', 'console_scripts', 'celeryctl')()
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/celeryctl.py", line 321, in main
    celeryctl().execute_from_commandline()
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/base.py", line 72, in execute_from_commandline
    return self.handle_argv(prog_name, argv[1:])
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/celeryctl.py", line 316, in handle_argv
    return self.execute(command, argv)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/celeryctl.py", line 306, in execute
    cls(app=self.app).run_from_argv(self.prog_name, argv)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/celeryctl.py", line 71, in run_from_argv
    self(_args, *_options.**dict**)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/celeryctl.py", line 45, in **call**
    self.run(_args, *_kwargs)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/celeryctl.py", line 268, in run
    .run("ping", *_dict(kwargs, quiet=True))
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/bin/celeryctl.py", line 241, in run
    replies = getattr(i, command)(_args[1:])
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/task/control.py", line 62, in ping
    return self._request("ping")
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/task/control.py", line 35, in _request
    timeout=self.timeout, reply=True))
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/task/control.py", line 211, in broadcast
    connection=connection, connect_timeout=connect_timeout)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/app/base.py", line 250, in _inner
    return fun(_args, *_kwargs)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/celery/task/control.py", line 205, in _do_broadcast
    channel=channel)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/kombu/pidbox.py", line 219, in _broadcast
    chan = channel or self.connection.channel()
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/kombu/connection.py", line 124, in channel
    chan = self.transport.create_channel(self.connection)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/kombu/connection.py", line 444, in connection
    self._connection = self._establish_connection()
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/kombu/connection.py", line 410, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/kombu/transport/pyamqplib.py", line 252, in establish_connection
    connect_timeout=conninfo.connect_timeout)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/kombu/transport/pyamqplib.py", line 51, in __init__
    super(Connection, self).**init**(_args, *_kwargs)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/amqplib/client_0_8/connection.py", line 125, in **init**
    self.transport = create_transport(host, connect_timeout, ssl)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/amqplib/client_0_8/transport.py", line 220, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/cmheisel/kardboardve/lib/python2.6/site-packages/amqplib/client_0_8/transport.py", line 58, in **init**
    self.sock.connect((host, port))
  File "<string>", line 1, in connect
socket.error: [Errno 111] Connection refused
(kardboardve)cmheisel@li169-12:~$ 

So with Flask-Celery it's picking up on the configuration that I did as far as broker and transport settings, but if I use just Celery then I'm guessing I'd have to duplicate that configuration into a celery.py and point celery's commands at it.

**Comment by ask** [comment] 2011-08-04 14:21
Trying to test this issue, but having problems getting it running.
When i Install Flask-Script it overwrites flaskext so celery is gone, if i install Flask-Celery  flaskext/script.py is gone. :(

**Comment by cmheisel** [comment] 2011-09-06 17:24
That is seriously frustrating. I worked around it my manually symlinking flaskext/celery.py into my site-packages flaskext.

Now I'm getting this:

> Traceback (most recent call last):
>  File "example/myapp.py", line 2, in <module>
>   from flaskext.celery import Celery
>  File "/Users/chris/.virtualenvs/flask-celery/lib/python2.7/site-packages/Flask_Script-0.3.1-py2.7.egg/flaskext/celery.py", line 16, in <module>
>    from celery.app import App, AppPickler, current_app as current_celery

I've got celery 2.3.1 installed (after doing a setup.py develop on flask-celery)

**Comment by ask** [comment] 2011-09-06 17:32
Install celery from git master.  It is seriously frustrating, but I'm not
able to work on this until it is possible to have two flask extensions installed at the same time :( 

## 

Ask Solem

**Comment by ask** [comment] 2011-09-06 17:37
I think maybe we should stop using flaskext, even if it means we don't conform to the flask extension rules.

  I was under the impression that everyone had agreed and decided that namespace packages are broken and shouldn't be used. So maybe that wouldn't be so bad anyway

## 

Ask Solem

**Comment by cmheisel** [comment] 2011-09-09 19:33
That seems like the better and more pythonic approach -- I don't know why
all flask-ish things need to be installed in flaskext's namespace.
Everything is done via importing so it's just a convention. A convention
that's breaking stuff :-(

**Comment by mitsuhiko** [comment] 2011-09-17 16:40
The problem is that they worked fine when we started doing them but pip's default unpacking of eggs breaks them again in combination with develop or other means to install them. I will consider something. Maybe the proper way is to change flask extensions to be importable from "flask_extname" instead of flaskext.extname.

**Comment by ask** [comment] 2011-10-28 23:58
I found the reason for the celeryctl problem.

I contributed a patch to Flask-Script so that commands could override how command-line options
was parsed, this commit was accepted and integrated, but in the recent version
it is simply gone.  Very strange.

I'm going to fork Flask-Script and upload a custom version to PyPI so that we can get this working
ASAP.

**Comment by ask** [comment] 2011-11-25 19:10
Fixed now.  We use the 'Flask-Script-fix' distribution instead, which installs itself as `flask.ext.script`.

You have to update your files to use 'flask.ext.script' instead of 'flaskext.script' (e.g. see updated examples/)

**Closed as completed by ask** 2011-11-25 19:10 UTC

**Comment by cmheisel** [comment] 2011-11-26 15:41
Thanks that's working perfectly!
